language: ko
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 50
  constrain_similarities: true
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.3
policies:
- name: RulePolicy
  core_fallback_action_name: "action_query_csv"
  enable_fallback_prediction: true
assistant_id: 20250812-093442-raw-metaphor
